version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: patineer
      MYSQL_DATABASE: asset
    ports:
      - "3306:3306"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin:latest              # ดึง Image ล่าสุดของ phpMyAdmin มาใช้
    container_name: asset_container        # ตั้งชื่อ Container
    restart: always
    environment:
      PMA_HOST: db                       # [สำคัญ] ใส่ชื่อ service ของ MySQL (ในที่นี้คือ db)
      PMA_PORT: 3306                     # Port ของ MySQL ข้างในระบบ Docker
      PMA_USER: root                     # User ที่ใช้ล็อกอิน
      PMA_PASSWORD: patineer  # รหัสผ่านที่ตรงกับตู้ MySQL ข้างบน
    ports:
      - "8088:80"                        # ผูกหน้าเว็บออกไปที่ Port 8080 ของเครื่องเรา